name: test_package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories(), Ncpu = 2L)
          remotes::install_cran("covr")
        shell: Rscript {0}
        
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        
      - name: BiocCheck
        run: |
          BiocManager::install("BiocCheck")
          BiocCheck::BiocCheck(".")
        shell: Rscript {0}
        
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

